apiVersion: batch/v1
kind: Job
metadata:
  name: {{ name }}
  namespace: {{ namespace }}
spec:
  completions: {{ replicas }}
  parallelism: {{ replicas }}
  backoffLimit: {{ backoffLimit }}
  # activeDeadlineSeconds: {{ activeDeadlineSeconds }}
  # Reference: https://kubernetes.io/docs/concepts/workloads/controllers/job/#ttl-mechanism-for-finished-jobs
  #   "Note that this TTL mechanism is alpha, with feature gate TTLAfterFinished. 
  #   For more information, see the documentation for TTL controller for 
  #   finished resources."
  # ttlSecondsAfterFinished: 30
  template:
    metadata:
      labels:
        type: "uws-job"
        jobId: {{ jobId }}
    spec:
      restartPolicy: Never
      securityContext:
        runAsUser: 73006
        runAsGroup: 73006
        # fsGroup: 73006
      volumes:
      - name: scratch
        persistentVolumeClaim:
          claimName: nfs-scratch-pvc
      - name: data
        persistentVolumeClaim:
          claimName: nfs-data-pvc
      - name: nfs-oods-comcam
        persistentVolumeClaim:
          claimName: nfs-oods-comcam-pvc
      containers:
      - name: {{ container_name }}
        image: {{ image }}
        imagePullPolicy: IfNotPresent
        command: {{ command }}
        env:
          - name: "DATA_DIR_COMCAM"
            value: "/data/lsstdata/comcam/oods/butler/repo"
          {% for env in environment %}
          - name: {{ env.name }}
            value: {{ env.value }}
          {% endfor %}
        volumeMounts:
        - name: scratch
          mountPath: /scratch/uws
          subPath: uws
        - name: data
          mountPath: /lsstdata/offline/teststand
          readOnly: true
        - name: nfs-oods-comcam
          mountPath: /data/lsstdata/comcam/oods/butler/repo
          # readOnly: true

